FROM tensorflow/tensorflow:2.3.1-gpu

LABEL version="1.0.0"
LABEL vendor="Bard's Way"
LABEL maintainer="benjamin.brihoum"
LABEL description="Bard's Way main container with python dependency and tensorflow2.3-GPU."

WORKDIR /

RUN apt-get update && apt-get install python-numpy ffmpeg -y

COPY requirement.txt .

RUN pip3 install -r requirement.txt
